apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
- ingress.yaml
images:
- name: nexus-repo.nexus.cloud.35.209.207.26.nip.io/test/flask-test
  newTag: "20230918052215"
